### ISSUE TITLE
TODOS for read_txt_Witec_ASCII

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.Witec#1]
- [x] find out better name - waiting for Ute's reply
- [x] provide axis labels 
  - [x] x axis units are in `$SpectrumHeader$XDataKind`
- [x] allow users to specify extra data to keep
- [x] unit testing
- [x] documentation

**Comment by eoduniyi** [comment]
I think Claudia and I cleared everything off of this list. Closing this now.
