### ISSUE TITLE
Rename all functions to use "_" instead of "."

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#12]
Rename all the functions like `read.txt.Witec()` into `read_txt_Witec()`.  In particular, function names should be the same as filenames that contain those functions, e.g., in https://github.com/r-hyperspec/hySpc.read.Witec/blob/develop/R/read_txt_Witec.R
https://github.com/r-hyperspec/hySpc.read.Witec/blob/16a57f09b1c149e43d3f31d9284f740bc808e825/R/read_txt_Witec.R#L24

There are several not renamed functions including `read.mat.Witec()`, `read.dat.Witec()`, and `read.txt.Witec()`.

**Comment by eoduniyi** [comment]
Created the branch `feature-12-rename.2_` to take care of this issue

**Comment by bryanhanson** [comment]
@cbeleites  @eoduniyi  has completed this issue but I was wondering if this change requires some kind of deprecation.  If no, please close this issue.

**Comment by GegznaV** [comment]
For exported functions only, these changes should be mentioned in `NEWS.md` in **hyperSpec** repo.

**Comment by GegznaV** [comment]
And when issue cbeleites/hyperSpec#263 is solved, I'll add proper deprecation messages to relevant functions in **hyperSpec** (as I did with **hySpc.ggplot2**).

**Comment by eoduniyi** [comment]
PR #26 closes this issue
