### ISSUE TITLE
In `DESCRIPTION`, use title case for title

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#13]
In `DESCRIPTION`, use title case otherwise it will not pacc CRAN checks:

`Title: File import Functions for Spectra in various ASCII/text file formats`

**Comment by bryanhanson** [comment]
Fixed in https://github.com/r-hyperspec/hySpc.read.txt/commit/d8221b7a6920977205642a4737dd8327bac840e2
