### ISSUE TITLE
Update fileio Vignette from the Perspective of hySpc.read.txt

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.Witec#19]
This issue could be potentially be raised several places, but it's going here for now.

As this package is reaching a completion point in the very near future, it's a good time to update `fileio.Rmd` that resides in `hyperSpec` (I will mention this issue over there).  I'm assigning to Erick as his fresh eyes will be a real advantage.

- [x] Examine the outline of the document and see if it flows logically.  Some of these vigs have grown by accretion and re-organization is in order. Repeat this process as you go along, it might be necessary to move things several times.
- [x] Read over the intro vignette for general "feel" and to know what's in there, so it can be referenced potentially, there may even be some parts that can be re-used (and possibly re-used via a common file that is inserted).  Please see https://github.com/cbeleites/hyperSpec/issues/261 as well.
- [x] Update the material that relates to `hySpc.read.txt` appropriately so it is current.
- [x] Go over the entire document for flow and clarity and user-friendliness, the latter from the perspective of a newish user. Edit as needed.

**Comment by eoduniyi** [comment]
@bryanhanson on the first pass of reading fileio.Rmd:

**Text:**
“Thus, once your data is in R’s workspace, creating a hyperSpec object is easy. I suggest wrapping the code to import your data and the line joining it into a hyperSpec object by your own import function. You are more than welcome to contribute such import code to package hyperSpec. Secion ?? discusses examples of custom import functions.”

**Comment:** Shouldn't "I" be replaced with "We": "We suggest wrapping the code..."

---
**Text:**
"The NIST (National Institute of Standards and Technology) has published a data base of basic atomic emission spectra see http://physics.nist.gov/PhysRefData/Handbook/periodictable.htm with emission lines tabulated in ASCII (HTML) files."

**Comment:** Can links be styled (i.e., [see here])(http://physics.nist.gov/PhysRefData/Handbook/periodictable.htm)

---
**Text:**
"Here’s an example [of] how to extract the data of the Hg strong lines file:"

**Comment:** I think it would benefit to add comments to each line for newbies and pros

---
**Text:**
"Many spectrometer manufacturers provide a function to export their spectra into ASCII files. The functions discussed above are written in a very general way[<s>,</s>] and are highly customizable. I recommend wrapping these calls with the appropriate settings for your spectra format in an import function. Please consider contributing such import filters to package hyperSpec: send me the documented code (for details see the box at the beginning of this document). If you are able to import data of any format not mentioned in this document (even without the need of new converters), please let me know (details again in the box at the beginning of this document)."

**Comment:** Shouldn't "I" be replaced with "We": "We recommend wrapping these calls..."

Other than that, I think the document is pretty well structured. There also appears to be "??" to indicate where sections need to be referenced.

**Comment by bryanhanson** [comment]
Some general comments:

* "We" is probably better since there is a team now.  You could check the intro vignette too (I re-wrote it but cannot remember just now any details).  Whatever you choose, be consistent with the "voice".
* Styling links, fixing cross references etc.  Look to the intro vignette for how this is done.  These documents are using a bookdown approach where the details of these markdown signals are actually different that basic markdown.  VG translated these documents from knitr to  bookdown but there are still a lot of places to fix the details (As I edited the intro vig, and then updated my own package  pkgdown site, I realized how in-flux the markdown/bookdown/blogdown world is.  Hopefully it becomes more standardized)
* VG implemented a means of inserting (and hiding) comments from developers and editors.  I actually eliminated most of these in the intro version as it evolved.  Those sections show up as colored boxes with outlines.  If you have trouble finding how he does this give me a holler.

**Comment by bryanhanson** [comment]
Code blocks like this one mark developer's comments, and there is a flag to display or not somewhere.

```
{block, type="note-t", echo=show_reviewers_notes}
```

**Comment by eoduniyi** [comment]
> Code blocks like this one mark developer's comments, and there is a flag to display or not somewhere.
> 
> ```
> {block, type="note-t", echo=show_reviewers_notes}
> ```

Got it!

**Comment by bryanhanson** [comment]
So use those blocks to write comments when you are not sure how to handle more significant or unclear items, then one of us can come along and respond/act.  Since you are actually working over in the `hyperSpec` repo leave these comments hidden since the vig is published when pushed. UPDATE: if you are on a separate branch it wont' be published unless we make other changes; build and review locally for now I guess.

**Comment by eoduniyi** [comment]
This has been settled with the PR #28
