### ISSUE TITLE
Use Github Actions to Move .tar.gz over to hySpc.pkgs

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.Witec#2]
To automatically deploy the results of building and checking, we need to:

- [ X] Do the building and checking using Github actions.  Right now GHA is used only for `pkgdown`
- [ ] Add an additional step that moves the completed `hySpc.read.Witec_xxx.tar.gz` over to `hySpc.pkgs`  I've researched this some, here's a few resources I've found:

* https://stackoverflow.com/a/59455293/633251 Looks like it might be the simplest approach but some details are not clear to me, and must be tested _in situ_. Be sure to read the comments on this answer.
* https://github.com/andstor/copycat-action
* https://github.com/marketplace/actions/copy-via-ssh (since we are copying between repos that we own I don't think it needs to be this complicated).

**Comment by eoduniyi** [comment]
On it!
