### ISSUE TITLE
Items from hyperSpec that should be dealt with here

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.Witec#21]
As far as I can see, the following issues present in `hyperSpec` should be addressed here at this time.

- [x] https://github.com/cbeleites/hyperSpec/issues/193
- [x] https://github.com/cbeleites/hyperSpec/issues/174
- [x] https://github.com/cbeleites/hyperSpec/issues/171
- [x] https://github.com/cbeleites/hyperSpec/issues/38

Please close over there as you tick them off.

**Comment by cbeleites** [comment]
**hyperSpec's** cbeleites/hyperSpec#38 needs to be looked into here, but the other import functions need to be checked as well. So @eoduniyi , please tick off here after checking the text import functions but leave it open in the **hyperSpec** repo (maybe comment there which ones are done/still need checking).

As for cbeleites/hyperSpec#174 I'm working on that in branch feature/more-unittest-data. @eoduniyi , if you want to work on that, it is right now probably easiest if you dig into unit test for the other text/ASCII import functions that you copied from **hyperSpec**.

**Comment by eoduniyi** [comment]
Okay, on it!

**Comment by eoduniyi** [comment]
The `check_con` function takes care of `hyperSpec` issue 38 for `hySpc.read.txt` the remaining `hyperSpec` issues on the todo list have been taken care of...
