### ISSUE TITLE
Move (copy) any remaining functions in hyperSpec that belong here.

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.read.Witec#22]
I believe this is what @GegznaV mentioned during the video call today.  I will assign to Erick as he's the one must up to date on this repo.

**Comment by eoduniyi** [comment]
@cbeleites and @GegznaV looking at the `hyperSpec` repo I saw that the following functions might still need to be copied over to `hySpc.read.txt`:

- [x] `fileio.optional.R`
- [x] `read.ini.R`
- [x] `read.mat.Witec.R`
- [x] `read.txt.Horiba.R`
- [x] `read.txt.long.R`
- [x] `read.txt.Reinshaw.R`
- [x] `read.txt.Shimandzu.R`
- [x] `read.txt.wide.R`

**Comment by GegznaV** [comment]
I wrote more specific instructions in a separate issue in hyperSpec (I did
not see this one). Plese, link these two issues.

2020 rugp. 18, an 12:10, Erick Oduniyi <notifications@github.com> rašė:

**Comment by eoduniyi** [comment]
This is the same as [issue #263](https://github.com/cbeleites/hyperSpec/issues/263) in `hyperSpec`

**Comment by eoduniyi** [comment]
PR #24 closes this issue
