### ISSUE TITLE
Add all authors of functions to the list of contributors

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#25]
In functions that read from ASCII files (some of them are not moved to this package yet, see cbeleites/hyperSpec#263) the authors of those functions (that are not C. Beleites) are mentioned. These people **must** apear in the list of contributors of this package.

**Comment by eoduniyi** [comment]
@GegznaV okay thank you. Will gladly do this.

**Comment by eoduniyi** [comment]
This issue was closed by PR #26 from hypSpc.read.txt
