### ISSUE TITLE
No warning in unit test

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#30]
For #27, I get this issue locally

![image](https://user-images.githubusercontent.com/12725868/91092376-9805fe80-e660-11ea-8745-7fc6a474b2ab.png)

**Comment by cbeleites** [comment]
Yes, I also found this and fixed it in 176fa7b.

**Comment by GegznaV** [comment]
👍

**Comment by GegznaV** [comment]
I ran this R-CMD check after pulling commit "Fix unit test locale". And instead 2 failed unit tests (as it was the case before pulling) only 1 was left. 

Were there several commits with the same name?

**Comment by cbeleites** [comment]
No, but only one of them could be located on my linux machine. I keep finding more of them on Win (hopefully fixed now) and MacOS via the CI...

Reminds me of the chemist's saying: when god invented bulk matter, the devil added surfaces. I think encodings as well.

**Comment by GegznaV** [comment]
It seems, that the issue is fixed now.
