### ISSUE TITLE
move read_mat_Witec() to hySpc.read.mat

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.Witec#40]
move `read.mat.Witec()` to **hySpc_read_mat**

**Comment by bryanhanson** [comment]
This might be done already...

**Comment by cbeleites** [comment]
- [x] check whether there is anything in here that is needed in `hySpc.read.mat::read_mat_Witec()`
- [x] if so, move that over to `hySpc.read.mat::read_mat_Witec()`
- [x] delete here
