### ISSUE TITLE
(re)move .spc test files

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.Witec#46]
There are non-ASCII files in directories `spc.Kaisermap` (needs to go to **hySpc.read.spc**) and `spc.Witec` (several file formats, including ASCII which should be kept but directory renamed accordingly).

This should be tackled only after the PRs https://github.com/r-hyperspec/hySpc.read.txt/pull/44 and https://github.com/r-hyperspec/hySpc.read.txt/pull/45 are merged.

- @sangttruong, can you take care of `spc.Kaisermap/`, please?
- @sangttruong, can you start with `spc.Witec` and notify me how far you get?

**Comment by GegznaV** [comment]
Why is this issue blocked? And what should be done to unblock it?

**Comment by cbeleites** [comment]
@GegznaV I noticed that we have PRs moving the example files. I think we need to sort out that mess first.

**Comment by GegznaV** [comment]
PR #44 is merged:
- #44

**Comment by GegznaV** [comment]
When these files are moved, please, write here the new destination where the files will be contained.

**Comment by sangttruong** [comment]
I remove spc.Kaisermap files. There files are in hySpc.read.spc/inst/extdata/spc.Kaisermap/

**Comment by sangttruong** [comment]
I remove spc.Witec files. There files are in hySpc.read.spc/inst/extdata/spc.Witec/

**Comment by sangttruong** [comment]
move spc file to hySpc.read.spc under spc.Witec folder, move mat file to hySpc.read.mat under mat.Witec folder, and move txt file to hySpc.read.txt under txt.Witec folder. @cbeleites can you please review and let me know what you think?
