### ISSUE TITLE
Use link to `hyperSpec` class in `@return`

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#68]
For functions, that return `hyperSpec` object, use link to `hyperSpec` class as follows:

```rmd
#' @return [hyperSpec][hyperSpec::hyperSpec-class()] object.
```

**Comment by bryanhanson** [comment]
Just a quick comment about this issue. I recently learned and began using `@template` for documentation that occurs a lot of places and which one might want to fine tune or change from time-to-time.  Very handy. Described [here](https://stackoverflow.com/a/15143507/633251).
